var surah_info = [
 {
   "number": 1,
   "arabic": "،الفاتحةأم الكتاب، أم القرآن، السبع المثاني، الحمد، الشفاء، سورة الصلاة، الأساس",
   "transliterated": "Al-Fātiḥah",
   "english": "The Opening",
   "num_verses": 7,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 5,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 2,
   "arabic": "البقرة",
   "transliterated": "Al-Baqara",
   "english": "The Cow",
   "num_verses": 286,
   "num_rukus": 40,
   "revelation": "Medinan",
   "chronological": 87,
   "letters": "Alif Lam Mim",
   "num_sajdas": 0,
   "num_pages": 48
 },
 {
   "number": 3,
   "arabic": "آل عمران",
   "transliterated": "Ali Imran",
   "english": "The House of Imran",
   "num_verses": 200,
   "num_rukus": 20,
   "revelation": "Medinan",
   "chronological": 89,
   "letters": "Alif Lam Mim",
   "num_sajdas": 0,
   "num_pages": 27
 },
 {
   "number": 4,
   "arabic": "النساء",
   "transliterated": "An-Nisa'",
   "english": "Women",
   "num_verses": 176,
   "num_rukus": 24,
   "revelation": "Medinan",
   "chronological": 92,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 29
 },
 {
   "number": 5,
   "arabic": "المائدة",
   "transliterated": "Al-Ma'ida",
   "english": "The Table Spread",
   "num_verses": 120,
   "num_rukus": 16,
   "revelation": "Medinan",
   "chronological": 112,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 22
 },
 {
   "number": 6,
   "arabic": "الأنعام",
   "transliterated": "Al-An'am",
   "english": "Cattle",
   "num_verses": 165,
   "num_rukus": 20,
   "revelation": "Meccan",
   "chronological": 55,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 23
 },
 {
   "number": 7,
   "arabic": "الأعراف",
   "transliterated": "Al-A'raf",
   "english": "The Heights",
   "num_verses": 206,
   "num_rukus": 24,
   "revelation": "Meccan",
   "chronological": 39,
   "letters": "Alif Lam Mim Sad",
   "num_sajdas": 1,
   "num_pages": 26
 },
 {
   "number": 8,
   "arabic": "الأنفال",
   "transliterated": "Al-Anfal",
   "english": "Spoils of War",
   "num_verses": 75,
   "num_rukus": 10,
   "revelation": "Medinan",
   "chronological": 88,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 9,
   "arabic": "،التوبةالبراءة",
   "transliterated": "At-Tawba",
   "english": "Repentance",
   "num_verses": 129,
   "num_rukus": 16,
   "revelation": "Medinan",
   "chronological": 113,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 21
 },
 {
   "number": 10,
   "arabic": "يونس",
   "transliterated": "Yunus",
   "english": "Jonah",
   "num_verses": 109,
   "num_rukus": 11,
   "revelation": "Meccan",
   "chronological": 51,
   "letters": "Alif Lam Ra",
   "num_sajdas": 0,
   "num_pages": 13
 },
 {
   "number": 11,
   "arabic": "هود",
   "transliterated": "Hud",
   "english": "Hud",
   "num_verses": 123,
   "num_rukus": 10,
   "revelation": "Meccan",
   "chronological": 52,
   "letters": "Alif Lam Ra",
   "num_sajdas": 0,
   "num_pages": 15
 },
 {
   "number": 12,
   "arabic": "يوسف",
   "transliterated": "Yusuf",
   "english": "Joseph",
   "num_verses": 111,
   "num_rukus": 12,
   "revelation": "Meccan",
   "chronological": 53,
   "letters": "Alif Lam Ra",
   "num_sajdas": 0,
   "num_pages": 14
 },
 {
   "number": 13,
   "arabic": "الرعد",
   "transliterated": "Ar-Ra'd",
   "english": "Thunder",
   "num_verses": 43,
   "num_rukus": 6,
   "revelation": "Medinan",
   "chronological": 96,
   "letters": "Alif Lam Mim Ra",
   "num_sajdas": 1,
   "num_pages": 6
 },
 {
   "number": 14,
   "arabic": "إبراهيم",
   "transliterated": "Ibrahim",
   "english": "Abraham",
   "num_verses": 52,
   "num_rukus": 7,
   "revelation": "Meccan",
   "chronological": 72,
   "letters": "Alif Lam Ra",
   "num_sajdas": 0,
   "num_pages": 7
 },
 {
   "number": 15,
   "arabic": "الحجر",
   "transliterated": "Al-Hijr",
   "english": "The City of Stone or The Rocky Plain",
   "num_verses": 99,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 54,
   "letters": "Alif Lam Ra",
   "num_sajdas": 0,
   "num_pages": 5
 },
 {
   "number": 16,
   "arabic": "،النحلالنعم",
   "transliterated": "An-Nahl",
   "english": "The Bee",
   "num_verses": 128,
   "num_rukus": 16,
   "revelation": "Meccan",
   "chronological": 70,
   "letters": "",
   "num_sajdas": 1,
   "num_pages": 15
 },
 {
   "number": 17,
   "arabic": "،الإسراءبني إسراءيل، سبحان",
   "transliterated": "Al-Isra'",
   "english": "The Night Journey",
   "num_verses": 111,
   "num_rukus": 12,
   "revelation": "Meccan",
   "chronological": 50,
   "letters": "",
   "num_sajdas": 1,
   "num_pages": 11
 },
 {
   "number": 18,
   "arabic": "الكهف",
   "transliterated": "Al-Kahf",
   "english": "The Cave",
   "num_verses": 110,
   "num_rukus": 12,
   "revelation": "Meccan",
   "chronological": 69,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 11
 },
 {
   "number": 19,
   "arabic": "مريم",
   "transliterated": "Maryam",
   "english": "Mary",
   "num_verses": 98,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 44,
   "letters": "Kaf Ha Ya 'Ain Sad",
   "num_sajdas": 1,
   "num_pages": 7
 },
 {
   "number": 20,
   "arabic": "طه",
   "transliterated": "Ta-Ha",
   "english": "Ta-Ha",
   "num_verses": 135,
   "num_rukus": 8,
   "revelation": "Meccan",
   "chronological": 45,
   "letters": "Ta Ha [notes 1]",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 21,
   "arabic": "الأنبياء",
   "transliterated": "Al-Anbiya'",
   "english": "The Prophets",
   "num_verses": 112,
   "num_rukus": 7,
   "revelation": "Meccan",
   "chronological": 73,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 22,
   "arabic": "الحج",
   "transliterated": "Al-Hajj",
   "english": "The Pilgrimage",
   "num_verses": 78,
   "num_rukus": 10,
   "revelation": "Medinan",
   "chronological": 103,
   "letters": "",
   "num_sajdas": 2,
   "num_pages": 10
 },
 {
   "number": 23,
   "arabic": "المؤمنون",
   "transliterated": "Al-Mu'minoon",
   "english": "The Believers",
   "num_verses": 118,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 74,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 8
 },
 {
   "number": 24,
   "arabic": "النور",
   "transliterated": "An-Nur",
   "english": "Light",
   "num_verses": 64,
   "num_rukus": 9,
   "revelation": "Medinan",
   "chronological": 102,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 25,
   "arabic": "الفرقان",
   "transliterated": "Al-Furqan",
   "english": "The Criterion",
   "num_verses": 77,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 42,
   "letters": "",
   "num_sajdas": 1,
   "num_pages": 7
 },
 {
   "number": 26,
   "arabic": "الشعراء",
   "transliterated": "Ash-Shu'ara",
   "english": "The Poets",
   "num_verses": 227,
   "num_rukus": 11,
   "revelation": "Meccan",
   "chronological": 47,
   "letters": "Ta Sin Mim",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 27,
   "arabic": "النمل",
   "transliterated": "An-Naml",
   "english": "The Ants",
   "num_verses": 93,
   "num_rukus": 7,
   "revelation": "Meccan",
   "chronological": 48,
   "letters": "Ta Sin",
   "num_sajdas": 1,
   "num_pages": 9
 },
 {
   "number": 28,
   "arabic": "القصص",
   "transliterated": "Al-Qasas",
   "english": "The Story",
   "num_verses": 88,
   "num_rukus": 9,
   "revelation": "Meccan",
   "chronological": 49,
   "letters": "Ta Sin Mim",
   "num_sajdas": 0,
   "num_pages": 11
 },
 {
   "number": 29,
   "arabic": "العنكبوت",
   "transliterated": "Al-Ankabut",
   "english": "The Spider",
   "num_verses": 69,
   "num_rukus": 7,
   "revelation": "Meccan",
   "chronological": 85,
   "letters": "Alif Lam Mim",
   "num_sajdas": 0,
   "num_pages": 9
 },
 {
   "number": 30,
   "arabic": "الروم",
   "transliterated": "Ar-Rum",
   "english": "Byzantium",
   "num_verses": 60,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 84,
   "letters": "Alif Lam Mim",
   "num_sajdas": 0,
   "num_pages": 7
 },
 {
   "number": 31,
   "arabic": "لقمان",
   "transliterated": "Luqman",
   "english": "Luqman",
   "num_verses": 34,
   "num_rukus": 4,
   "revelation": "Meccan",
   "chronological": 57,
   "letters": "Alif Lam Mim",
   "num_sajdas": 0,
   "num_pages": 4
 },
 {
   "number": 32,
   "arabic": "،السجدةالمضاجع، الم تنزيل",
   "transliterated": "As-Sajda",
   "english": "Prostration",
   "num_verses": 30,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 75,
   "letters": "Alif Lam Mim",
   "num_sajdas": 1,
   "num_pages": 3
 },
 {
   "number": 33,
   "arabic": "الأحزاب",
   "transliterated": "Al-Ahzab",
   "english": "The Confederates",
   "num_verses": 73,
   "num_rukus": 9,
   "revelation": "Medinan",
   "chronological": 90,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 34,
   "arabic": "سبأ",
   "transliterated": "Saba'",
   "english": "Sheba",
   "num_verses": 54,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 58,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 7
 },
 {
   "number": 35,
   "arabic": "،فاطرالملائكة",
   "transliterated": "Fatir",
   "english": "The Originator",
   "num_verses": 45,
   "num_rukus": 5,
   "revelation": "Meccan",
   "chronological": 43,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 6
 },
 {
   "number": 36,
   "arabic": "يس",
   "transliterated": "Ya Seen",
   "english": "Ya Seen",
   "num_verses": 83,
   "num_rukus": 5,
   "revelation": "Meccan",
   "chronological": 41,
   "letters": "Ya Sin [notes 2]",
   "num_sajdas": 0,
   "num_pages": 6
 },
 {
   "number": 37,
   "arabic": "الصافات",
   "transliterated": "As-Saffat",
   "english": "Those Ranged in Ranks",
   "num_verses": 182,
   "num_rukus": 5,
   "revelation": "Meccan",
   "chronological": 56,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 7
 },
 {
   "number": 38,
   "arabic": "،صداوود",
   "transliterated": "Sad",
   "english": "Sad",
   "num_verses": 88,
   "num_rukus": 5,
   "revelation": "Meccan",
   "chronological": 38,
   "letters": "Sad",
   "num_sajdas": 1,
   "num_pages": 5
 },
 {
   "number": 39,
   "arabic": "،الزمرالغرف",
   "transliterated": "Az-Zumar",
   "english": "The Crowds",
   "num_verses": 75,
   "num_rukus": 8,
   "revelation": "Meccan",
   "chronological": 59,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 9
 },
 {
   "number": 40,
   "arabic": "،غافرالمؤمن، الفضل",
   "transliterated": "Ghafir",
   "english": "The Forgiver",
   "num_verses": 85,
   "num_rukus": 9,
   "revelation": "Meccan",
   "chronological": 60,
   "letters": "Ha Mim",
   "num_sajdas": 0,
   "num_pages": 10
 },
 {
   "number": 41,
   "arabic": "،فصلتحم سجدة، المصابيح، الأقوات",
   "transliterated": "Fussilat",
   "english": "Expounded",
   "num_verses": 54,
   "num_rukus": 6,
   "revelation": "Meccan",
   "chronological": 61,
   "letters": "Ha Mim",
   "num_sajdas": 1,
   "num_pages": 6
 },
 {
   "number": 42,
   "arabic": "،الشورىحم عسق",
   "transliterated": "Ash-Shura",
   "english": "Counsel",
   "num_verses": 53,
   "num_rukus": 5,
   "revelation": "Meccan",
   "chronological": 62,
   "letters": "Ha Mim 'Ain Sin Qaf",
   "num_sajdas": 0,
   "num_pages": 6
 },
 {
   "number": 43,
   "arabic": "الزخرف",
   "transliterated": "Az-Zukhruf",
   "english": "Gold Ornaments",
   "num_verses": 89,
   "num_rukus": 7,
   "revelation": "Meccan",
   "chronological": 63,
   "letters": "Ha Mim",
   "num_sajdas": 0,
   "num_pages": 7
 },
 {
   "number": 44,
   "arabic": "الدخان",
   "transliterated": "Ad-Dukhan",
   "english": "Smoke",
   "num_verses": 59,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 64,
   "letters": "Ha Mim",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 45,
   "arabic": "،الجاثيةالشريعة",
   "transliterated": "Al-Jathiya",
   "english": "Kneeling",
   "num_verses": 37,
   "num_rukus": 4,
   "revelation": "Meccan",
   "chronological": 65,
   "letters": "Ha Mim",
   "num_sajdas": 0,
   "num_pages": 4
 },
 {
   "number": 46,
   "arabic": "الأحقاف",
   "transliterated": "Al-Ahqaf",
   "english": "The Sand Dunes",
   "num_verses": 35,
   "num_rukus": 4,
   "revelation": "Meccan",
   "chronological": 66,
   "letters": "Ha Mim",
   "num_sajdas": 0,
   "num_pages": 5
 },
 {
   "number": 47,
   "arabic": "،محمدالقتال",
   "transliterated": "Muhammad",
   "english": "Muhammad",
   "num_verses": 38,
   "num_rukus": 4,
   "revelation": "Medinan",
   "chronological": 95,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 4
 },
 {
   "number": 48,
   "arabic": "الفتح",
   "transliterated": "Al-Fath",
   "english": "Victory",
   "num_verses": 29,
   "num_rukus": 4,
   "revelation": "Medinan",
   "chronological": 111,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 5
 },
 {
   "number": 49,
   "arabic": "الحجرات",
   "transliterated": "Al-Hujurat",
   "english": "The Private Chambers",
   "num_verses": 18,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 106,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 50,
   "arabic": "،قالباسقات",
   "transliterated": "Qaf",
   "english": "Qaf",
   "num_verses": 45,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 34,
   "letters": "Qaf",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 51,
   "arabic": "الذاريات",
   "transliterated": "Adh-Dhariyat",
   "english": "The Scattering Winds",
   "num_verses": 60,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 67,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 52,
   "arabic": "الطور",
   "transliterated": "At-Tur",
   "english": "The Mountain",
   "num_verses": 49,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 76,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 53,
   "arabic": "النجم",
   "transliterated": "An-Najm",
   "english": "The Star",
   "num_verses": 62,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 23,
   "letters": "",
   "num_sajdas": 1,
   "num_pages": 3
 },
 {
   "number": 54,
   "arabic": "،القمراقتربت الساعة",
   "transliterated": "Al-Qamar",
   "english": "The Moon",
   "num_verses": 55,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 37,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 55,
   "arabic": "الرحمن",
   "transliterated": "Ar-Rahman",
   "english": "The Compassionate",
   "num_verses": 78,
   "num_rukus": 3,
   "revelation": "Medinan",
   "chronological": 97,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 56,
   "arabic": "الواقعة",
   "transliterated": "Al-Waqi'a",
   "english": "The Inevitable",
   "num_verses": 96,
   "num_rukus": 3,
   "revelation": "Meccan",
   "chronological": 46,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 57,
   "arabic": "الحديد",
   "transliterated": "Al-Hadid",
   "english": "Iron",
   "num_verses": 29,
   "num_rukus": 4,
   "revelation": "Medinan",
   "chronological": 94,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 4
 },
 {
   "number": 58,
   "arabic": "،المجادلةالظهار",
   "transliterated": "Al-Mujadila",
   "english": "She who Disputes",
   "num_verses": 22,
   "num_rukus": 3,
   "revelation": "Medinan",
   "chronological": 105,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3
 },
 {
   "number": 59,
   "arabic": "،الحشربنو نضير",
   "transliterated": "Al-Hashr",
   "english": "The Gathering",
   "num_verses": 24,
   "num_rukus": 3,
   "revelation": "Medinan",
   "chronological": 101,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 3.5
 },
 {
   "number": 60,
   "arabic": "،الممتحنةالامتحان، المودة",
   "transliterated": "Al-Mumtahina",
   "english": "She who is Examined",
   "num_verses": 13,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 91,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2.5
 },
 {
   "number": 61,
   "arabic": "،الصفالحواريون، عيسى",
   "transliterated": "As-Saff",
   "english": "The Ranks",
   "num_verses": 14,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 109,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 62,
   "arabic": "الجمعة",
   "transliterated": "Al-Jumu'a",
   "english": "The Congregation",
   "num_verses": 11,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 110,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 63,
   "arabic": "المنافقون",
   "transliterated": "Al-Munafiqun",
   "english": "The Hypocrites",
   "num_verses": 11,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 104,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 64,
   "arabic": "التغابن",
   "transliterated": "At-Taghabun",
   "english": "Mutual Dispossession",
   "num_verses": 18,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 108,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 65,
   "arabic": "،الطلاقسورة النساء القصرى",
   "transliterated": "At-Talaq",
   "english": "Divorce",
   "num_verses": 12,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 99,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 66,
   "arabic": "،التحريملما تحرم، المتحرم، سورة النبي",
   "transliterated": "At-Tahrim",
   "english": "Forbiddance",
   "num_verses": 12,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 107,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 67,
   "arabic": "،الملكتبارك، تبارك الذي بيده الملك، المانع، المنجية",
   "transliterated": "Al-Mulk",
   "english": "Dominion",
   "num_verses": 30,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 77,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2.5
 },
 {
   "number": 68,
   "arabic": "القلم",
   "transliterated": "Al-Qalam",
   "english": "The Pen",
   "num_verses": 52,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 2,
   "letters": "Nun",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 69,
   "arabic": "الحاقة",
   "transliterated": "Al-Haqqa",
   "english": "The Undeniable Reality",
   "num_verses": 52,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 78,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 70,
   "arabic": "،المعارجالمواقع، سأل",
   "transliterated": "Al-Ma'arij",
   "english": "The Ascending Ways",
   "num_verses": 44,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 79,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 71,
   "arabic": "نوح",
   "transliterated": "Nuh",
   "english": "Noah",
   "num_verses": 28,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 71,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 72,
   "arabic": "الجن",
   "transliterated": "Al-Jinn",
   "english": "The Jinn",
   "num_verses": 28,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 40,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 73,
   "arabic": "المزمل",
   "transliterated": "Al-Muzzammil",
   "english": "The Enwrapped One",
   "num_verses": 20,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 3,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 74,
   "arabic": "المدثر",
   "transliterated": "Al-Muddathir",
   "english": "The Covered One",
   "num_verses": 56,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 4,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 75,
   "arabic": "،القيامةلا أقسم",
   "transliterated": "Al-Qiyama",
   "english": "Resurrection",
   "num_verses": 40,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 31,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 76,
   "arabic": "،الإنسانهل أتى، الدهر، الأبرار",
   "transliterated": "Al-Insan",
   "english": "The Human",
   "num_verses": 31,
   "num_rukus": 2,
   "revelation": "Medinan",
   "chronological": 98,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 2
 },
 {
   "number": 77,
   "arabic": "المرسلات",
   "transliterated": "Al-Mursalat",
   "english": "Those Sent Forth",
   "num_verses": 50,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 33,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 78,
   "arabic": "،النبأالمعصرات، التساءل",
   "transliterated": "An-Naba'",
   "english": "The Tiding",
   "num_verses": 40,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 80,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 79,
   "arabic": "،النازعاتالساهرة، الطامة",
   "transliterated": "An-Nazi'at",
   "english": "The Snatchers",
   "num_verses": 46,
   "num_rukus": 2,
   "revelation": "Meccan",
   "chronological": 81,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1.5
 },
 {
   "number": 80,
   "arabic": "،عبسالصاخة، السفرة",
   "transliterated": "Abasa",
   "english": "He Frowned",
   "num_verses": 42,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 24,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 81,
   "arabic": "التكوير",
   "transliterated": "At-Takawir",
   "english": "The Enfolding",
   "num_verses": 29,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 7,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 82,
   "arabic": "الإنفطار",
   "transliterated": "Al-Infitar",
   "english": "The Splitting",
   "num_verses": 19,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 82,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 83,
   "arabic": "المطففين",
   "transliterated": "Al-Mutaffifeen",
   "english": "The Defrauders",
   "num_verses": 36,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 86,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 84,
   "arabic": "،الإنشقاقانشقت",
   "transliterated": "Al-Inshiqaq",
   "english": "The Bursting Open",
   "num_verses": 25,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 83,
   "letters": "",
   "num_sajdas": 1,
   "num_pages": 1
 },
 {
   "number": 85,
   "arabic": "البروج",
   "transliterated": "Al-Burooj",
   "english": "The Constellations",
   "num_verses": 22,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 27,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 86,
   "arabic": "الطارق",
   "transliterated": "At-Tariq",
   "english": "The Night Visitant or The Morning Star",
   "num_verses": 17,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 36,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 87,
   "arabic": "الأعلى",
   "transliterated": "Al-A'la",
   "english": "The Highest",
   "num_verses": 19,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 8,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 88,
   "arabic": "الغاشية",
   "transliterated": "Al-Ghashiya",
   "english": "The Overwhelming Event",
   "num_verses": 26,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 68,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 89,
   "arabic": "الفجر",
   "transliterated": "Al-Fajr",
   "english": "The Dawn",
   "num_verses": 30,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 10,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 1
 },
 {
   "number": 90,
   "arabic": "البلد",
   "transliterated": "Al-Balad",
   "english": "The City",
   "num_verses": 20,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 35,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 91,
   "arabic": "الشمس",
   "transliterated": "Ash-Shams",
   "english": "The Sun",
   "num_verses": 15,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 26,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 92,
   "arabic": "الليل",
   "transliterated": "Al-Lail",
   "english": "The Night",
   "num_verses": 21,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 9,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 93,
   "arabic": "الضحى",
   "transliterated": "Ad-Dhuha",
   "english": "The Morning Brightness",
   "num_verses": 11,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 11,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 94,
   "arabic": "،الشرحالانشراح",
   "transliterated": "Ash-Sharh",
   "english": "Expansion",
   "num_verses": 8,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 12,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 95,
   "arabic": "التين",
   "transliterated": "At-Teen",
   "english": "The Fig",
   "num_verses": 8,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 28,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 96,
   "arabic": "،العلقاقرأ",
   "transliterated": "Al-Alaq",
   "english": "The Blood Clot",
   "num_verses": 19,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 1,
   "letters": "",
   "num_sajdas": 1,
   "num_pages": 0.5
 },
 {
   "number": 97,
   "arabic": "القدر",
   "transliterated": "Al-Qadr",
   "english": "The Night of Power",
   "num_verses": 5,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 25,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 98,
   "arabic": "،البينةلم يكن",
   "transliterated": "Al-Bayyina",
   "english": "The Clear Proof",
   "num_verses": 8,
   "num_rukus": 1,
   "revelation": "Medinan",
   "chronological": 100,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 99,
   "arabic": "الزلزلة",
   "transliterated": "Az-Zalzala",
   "english": "The Earthquake",
   "num_verses": 8,
   "num_rukus": 1,
   "revelation": "Medinan",
   "chronological": 93,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 100,
   "arabic": "العاديات",
   "transliterated": "Al-'Adiyat",
   "english": "The Chargers",
   "num_verses": 11,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 14,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 101,
   "arabic": "القارعة",
   "transliterated": "Al-Qari'a",
   "english": "The Catastrophe",
   "num_verses": 11,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 30,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 102,
   "arabic": "التكاثر",
   "transliterated": "At-Takathur",
   "english": "Vying for Increase",
   "num_verses": 8,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 16,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.5
 },
 {
   "number": 103,
   "arabic": "العصر",
   "transliterated": "Al-'Asr",
   "english": "Time",
   "num_verses": 3,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 13,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 104,
   "arabic": "الهمزة",
   "transliterated": "Al-Humaza",
   "english": "The Slanderer",
   "num_verses": 9,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 32,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 105,
   "arabic": "الفيل",
   "transliterated": "Al-Feel",
   "english": "The Elephant",
   "num_verses": 5,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 19,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 106,
   "arabic": "قريش",
   "transliterated": "Quraysh",
   "english": "Quraysh",
   "num_verses": 4,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 29,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 107,
   "arabic": "الماعون",
   "transliterated": "Al-Ma'oon",
   "english": "Assistance",
   "num_verses": 7,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 17,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 108,
   "arabic": "الكوثر",
   "transliterated": "Al-Kawthar",
   "english": "Abundance",
   "num_verses": 3,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 15,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 109,
   "arabic": "الكافرون",
   "transliterated": "Al-Kafiroon",
   "english": "Disbelievers",
   "num_verses": 6,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 18,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 110,
   "arabic": "النصر",
   "transliterated": "An-Nasr",
   "english": "Help",
   "num_verses": 3,
   "num_rukus": 1,
   "revelation": "Medinan",
   "chronological": 114,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 111,
   "arabic": "،المسداللهب",
   "transliterated": "Al-Masad",
   "english": "Palm Fiber",
   "num_verses": 5,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 6,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 112,
   "arabic": "،الإخلاصالمنفرة، النجاة، المعرفة، المذكرة، نور القرآن",
   "transliterated": "Al-Ikhlas",
   "english": "Sincerity",
   "num_verses": 4,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 22,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 113,
   "arabic": "الفلق",
   "transliterated": "Al-Falaq",
   "english": "Daybreak",
   "num_verses": 5,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 20,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 },
 {
   "number": 114,
   "arabic": "الناس",
   "transliterated": "An-Nas",
   "english": "Mankind",
   "num_verses": 6,
   "num_rukus": 1,
   "revelation": "Meccan",
   "chronological": 21,
   "letters": "",
   "num_sajdas": 0,
   "num_pages": 0.33
 }
]